"""
Meeting Notes generator.
Reads transcript files (fetch phase) or renders HTML + TXT from a pre-generated summary (render phase).
AI generation is handled by the calling skill (Claude Code as Meeting Facilitator).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from src.config.settings import Settings
from src.utils.date_utils import now_str, today_str
from src.utils.file_utils import (
    ensure_dir,
    get_transcript_files,
    read_text,
    sanitize_filename,
    write_text,
)


# ---------------------------------------------------------------------------
# Domain models
# ---------------------------------------------------------------------------

@dataclass
class ActionItem:
    owner: str
    item: str
    due_date: str


@dataclass
class Attendee:
    name: str
    role: str


@dataclass
class DiscussionPoint:
    title: str
    description: str
    details: list[str]


@dataclass
class MeetingNotesSummary:
    title: str
    date: str
    time: str
    duration: str
    format: str
    attendees: list[Attendee]
    agenda_items: list[str]
    discussion_points: list[DiscussionPoint]
    key_decisions: list[str]
    action_items: list[ActionItem]
    open_items: list[str]
    next_steps: list[str]
    next_meeting: str
    summary: str
    raw_transcript_name: str

    @classmethod
    def from_dict(cls, data: dict, filename: str = "transcript") -> "MeetingNotesSummary":
        action_items = [
            ActionItem(owner=ai.get("owner", "TBD"), item=ai.get("item", ""), due_date=ai.get("due_date", "TBD"))
            for ai in data.get("action_items", [])
        ]
        raw_attendees = data.get("attendees", [])
        attendees = []
        for att in raw_attendees:
            if isinstance(att, dict):
                attendees.append(Attendee(name=att.get("name", ""), role=att.get("role", "Participant")))
            elif isinstance(att, str):
                attendees.append(Attendee(name=att, role="Participant"))
        discussion_points = [
            DiscussionPoint(title=dp.get("title", ""), description=dp.get("description", ""), details=dp.get("details", []))
            for dp in data.get("discussion_points", [])
        ]
        return cls(
            title=data.get("title", "Meeting Notes"),
            date=data.get("date", "Not specified"),
            time=data.get("time", "Not specified"),
            duration=data.get("duration", "Not specified"),
            format=data.get("format", "Not specified"),
            attendees=attendees,
            agenda_items=data.get("agenda_items", []),
            discussion_points=discussion_points,
            key_decisions=data.get("key_decisions", []),
            action_items=action_items,
            open_items=data.get("open_items", []),
            next_steps=data.get("next_steps", []),
            next_meeting=data.get("next_meeting", "Not scheduled"),
            summary=data.get("summary", ""),
            raw_transcript_name=filename,
        )


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

class MeetingNotesGenerator:
    """
    Two-phase pipeline:
      Phase 1 — read_transcript(s)(): reads transcript file(s) → transcript_data dict
      Phase 2 — render_from_summary(): summary dict (generated by skill) → HTML + TXT
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._jinja = Environment(
            loader=FileSystemLoader(settings.paths.templates_dir),
            autoescape=False,
        )

    # ------------------------------------------------------------------
    # Phase 1: Read transcript(s)
    # ------------------------------------------------------------------

    def read_transcript(self, filename: str) -> dict:
        """Read a single transcript file. Returns a JSON-serialisable dict."""
        transcript_dir = Path(self._settings.paths.input_transcripts)
        transcript_path = transcript_dir / filename
        if not transcript_path.exists():
            raise FileNotFoundError(
                f"Transcript not found: {transcript_path}\n"
                f"Place your .txt transcript files in '{self._settings.paths.input_transcripts}/'."
            )
        print(f"  Reading transcript: {filename}")
        return {"filename": filename, "stem": transcript_path.stem, "transcript_text": read_text(transcript_path)}

    def read_all_transcripts(self) -> list[dict]:
        """Read all .txt transcripts. Returns a list of transcript dicts."""
        files = get_transcript_files(self._settings.paths.input_transcripts)
        if not files:
            print(f"  No transcript files found in '{self._settings.paths.input_transcripts}/'.")
            return []
        results = []
        for path in files:
            print(f"  Reading transcript: {path.name}")
            results.append({"filename": path.name, "stem": path.stem, "transcript_text": read_text(path)})
        return results

    # ------------------------------------------------------------------
    # Phase 2: Render from AI-generated summary
    # ------------------------------------------------------------------

    def render_from_summary(self, summary_data: dict, stem: str) -> tuple[str, str]:
        """
        Render HTML + TXT from a summary dict generated by the skill.
        Returns (txt_filepath, html_filepath).
        """
        filename = summary_data.get("raw_transcript_name", stem)
        summary = MeetingNotesSummary.from_dict(summary_data, filename=filename)
        html_content = self._render_html(summary)
        txt_content = self._render_txt(summary)
        txt_path, html_path = self._write_outputs(summary, stem, html_content, txt_content)
        print(f"  Written: {txt_path}")
        print(f"  Written: {html_path}")
        return str(txt_path), str(html_path)

    # ------------------------------------------------------------------
    # Internal rendering
    # ------------------------------------------------------------------

    def _render_html(self, summary: MeetingNotesSummary) -> str:
        template = self._jinja.get_template("meeting_notes.html.j2")
        return template.render(summary=summary, generated_date=now_str(), branding=self._settings.branding)

    def _render_txt(self, summary: MeetingNotesSummary) -> str:
        lines: list[str] = []
        sep = "=" * 60
        lines += [sep, f"MEETING NOTES — {summary.title}", f"Date: {summary.date}"]
        if summary.time != "Not specified":
            lines.append(f"Time: {summary.time}")
        if summary.duration != "Not specified":
            lines.append(f"Duration: {summary.duration}")
        if summary.format != "Not specified":
            lines.append(f"Format: {summary.format}")
        lines += [f"Transcript: {summary.raw_transcript_name}", sep, ""]
        if summary.summary:
            lines += ["EXECUTIVE SUMMARY", "-" * 40, summary.summary, ""]
        if summary.attendees:
            lines += ["ATTENDEES", "-" * 40]
            for person in summary.attendees:
                lines.append(f"  {person.name} — {person.role}")
            lines.append("")
        if summary.agenda_items:
            lines += ["AGENDA", "-" * 40]
            for i, item in enumerate(summary.agenda_items, 1):
                lines.append(f"  {i}. {item}")
            lines.append("")
        if summary.discussion_points:
            lines += ["DISCUSSION POINTS", "-" * 40]
            for dp in summary.discussion_points:
                lines.append(f"  [{dp.title}]")
                if dp.description:
                    lines.append(f"    {dp.description}")
                for detail in dp.details:
                    lines.append(f"    - {detail}")
                lines.append("")
        if summary.key_decisions:
            lines += ["DECISIONS MADE", "-" * 40]
            for decision in summary.key_decisions:
                lines.append(f"  DECIDED: {decision}")
            lines.append("")
        if summary.action_items:
            lines += ["ACTION ITEMS", "-" * 40]
            for i, ai in enumerate(summary.action_items, 1):
                lines.append(f"  {i}. {ai.item}")
                lines.append(f"     Owner: {ai.owner}  |  Due: {ai.due_date}")
            lines.append("")
        if summary.open_items:
            lines += ["OPEN ITEMS / PARKING LOT", "-" * 40]
            for item in summary.open_items:
                lines.append(f"  ! {item}")
            lines.append("")
        if summary.next_steps:
            lines += ["NEXT STEPS", "-" * 40]
            for step in summary.next_steps:
                lines.append(f"  > {step}")
            lines.append("")
        if summary.next_meeting and summary.next_meeting != "Not scheduled":
            lines += ["NEXT MEETING", "-" * 40, f"  {summary.next_meeting}", ""]
        lines += [sep, f"Generated by SE-DevTools — {self._settings.branding.company_name}"]
        return "\n".join(lines)

    def _write_outputs(self, summary: MeetingNotesSummary, transcript_stem: str, html: str, txt: str) -> tuple[Path, Path]:
        safe_stem = sanitize_filename(transcript_stem)
        date_str = today_str(self._settings.output.date_format)
        base_name = self._settings.output.meeting_notes_filename_pattern.format(
            transcript_stem=safe_stem, date=date_str,
        )
        out_dir = ensure_dir(self._settings.paths.output_meeting_notes)
        return write_text(txt, out_dir / f"{base_name}.txt"), write_text(html, out_dir / f"{base_name}.html")
